apiVersion: apps/v1
kind: Deployment
metadata:
  name: damp-leaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitter-shadow
  template:
    metadata:
      labels:
        app: frosty-grass
    spec:
      containers:
      - image: okteto.dev/restless-wind:latest
        name: restless-wind
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "https://www.youtube.com"
        - name: Vless_UUID
          value: "0253d629-a2f6-4afa-8e6a-750fa03998fc"
        - name: Vless_Path
          value: "/hoem4te"
        - name: Vmess_UUID
          value: "970e9ce7-8698-4b6f-a215-246c667adea7"
        - name: Vmess_Path
          value: "/djei7ds"
        - name: Share_Path
          value: "/noenslie"
