apiVersion: v1
kind: Service
metadata:
  name: damp-leaf
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "damp-leaf"
    port: 8080
  selector:
    app: damp-leaf
